'use strict';var ba,ca=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},da=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ea(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var fa=ea(this);function m(a,b){if(b)a:{var c=fa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&da(c,a,{configurable:!0,writable:!0,value:b})}}var ha;
if(typeof Object.setPrototypeOf=="function")ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=ha;
function p(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ha=b.prototype}function ma(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ma(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function na(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function r(){this.F=!1;this.o=null;this.l=void 0;this.h=1;this.u=this.v=0;this.I=this.j=null}function oa(a){if(a.F)throw new TypeError("Generator is already running");a.F=!0}
r.prototype.H=function(a){this.l=a};function pa(a,b){a.j={Y:b,isException:!0};a.h=a.v||a.u}r.prototype.getNextAddressJsc=function(){return this.h};r.prototype.getYieldResultJsc=function(){return this.l};r.prototype.return=function(a){this.j={return:a};this.h=this.u};r.prototype["return"]=r.prototype.return;r.prototype.N=function(a){this.j={G:a};this.u<a?(this.h=a,this.j=null):this.h=this.u};r.prototype.jumpThroughFinallyBlocks=r.prototype.N;r.prototype.i=function(a,b){this.h=b;return{value:a}};
r.prototype.yield=r.prototype.i;r.prototype.O=function(a,b){a=q(a);var c=a.next();na(c);if(c.done)this.l=c.value,this.h=b;else return this.o=a,this.i(c.value,b)};r.prototype.yieldAll=r.prototype.O;r.prototype.G=function(a){this.h=a};r.prototype.jumpTo=r.prototype.G;r.prototype.D=function(){this.h=0};r.prototype.jumpToEnd=r.prototype.D;r.prototype.C=function(a,b){this.v=a;b!=void 0&&(this.u=b)};r.prototype.setCatchFinallyBlocks=r.prototype.C;r.prototype.L=function(a){this.v=0;this.u=a||0};
r.prototype.setFinallyBlock=r.prototype.L;r.prototype.B=function(a,b){this.h=a;this.v=b||0};r.prototype.leaveTryBlock=r.prototype.B;r.prototype.A=function(a){this.v=a||0;a=this.j.Y;this.j=null;return a};r.prototype.enterCatchBlock=r.prototype.A;r.prototype.J=function(a,b,c){c?this.I[c]=this.j:this.I=[this.j];this.v=a||0;this.u=b||0;this.j=null};r.prototype.enterFinallyBlock=r.prototype.J;
r.prototype.K=function(a,b){b=this.I.splice(b||0)[0];(b=this.j=this.j||b)?b.isException?this.h=this.v||this.u:b.G!=void 0&&this.u<b.G?(this.h=b.G,this.j=null):this.h=this.u:this.h=a};r.prototype.leaveFinallyBlock=r.prototype.K;r.prototype.M=function(a){return new qa(a)};r.prototype.forIn=r.prototype.M;function qa(a){this.j=a;this.h=[];for(var b in a)this.h.push(b);this.h.reverse()}qa.prototype.i=function(){for(;this.h.length>0;){var a=this.h.pop();if(a in this.j)return a}return null};
qa.prototype.getNext=qa.prototype.i;function ra(a){this.h=new r;this.i=a}function sa(a,b){oa(a.h);var c=a.h.o;if(c)return ta(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.h.return);a.h.return(b);return ua(a)}function ta(a,b,c,d){try{var e=b.call(a.h.o,c);na(e);if(!e.done)return a.h.F=!1,e;var f=e.value}catch(g){return a.h.o=null,pa(a.h,g),ua(a)}a.h.o=null;d.call(a.h,f);return ua(a)}
function ua(a){for(;a.h.h;)try{var b=a.i(a.h);if(b)return a.h.F=!1,{value:b.value,done:!1}}catch(c){a.h.l=void 0,pa(a.h,c)}a.h.F=!1;if(a.h.j){b=a.h.j;a.h.j=null;if(b.isException)throw b.Y;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){oa(a.h);a.h.o?b=ta(a,a.h.o.next,b,a.h.H):(a.h.H(b),b=ua(a));return b};this.throw=function(b){oa(a.h);if(a.h.o){var c=a.h.o["throw"];if(c)var d=ta(a,c,b,a.h.H);else{b=a.h.o;a.h.o=null;try{b["return"]&&(d=b["return"](),na(d)),pa(a.h,new TypeError("The iterator does not provide a 'throw' method."))}catch(e){pa(a.h,e)}d=ua(a)}}else pa(a.h,b),d=ua(a);return d};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}}
function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}function t(a){return wa(new va(new ra(a)))}m("Reflect.setPrototypeOf",function(a){return a?a:la?function(b,c){try{return la(b,c),!0}catch(d){return!1}}:null});
m("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.h=f;da(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
m("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");da(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return xa(ma(this))}});return a});function xa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
m("Promise",function(a){function b(g){this.i=0;this.j=void 0;this.h=[];this.v=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.h=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.i=function(g){if(this.h==null){this.h=[];var h=this;this.j(function(){h.o()})}this.h.push(g)};var e=fa.setTimeout;c.prototype.j=function(g){e(g,0)};c.prototype.o=function(){for(;this.h&&this.h.length;){var g=this.h;this.h=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.l(l)}}}this.h=null};c.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(l){return function(n){k||(k=!0,l.call(h,n))}}var h=this,k=!1;return{resolve:g(this.F),reject:g(this.o)}};b.prototype.F=function(g){if(g===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.I(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.D(g):this.u(g)}};
b.prototype.D=function(g){var h=void 0;try{h=g.then}catch(k){this.o(k);return}typeof h=="function"?this.J(h,g):this.u(g)};b.prototype.o=function(g){this.A(2,g)};b.prototype.u=function(g){this.A(1,g)};b.prototype.A=function(g,h){if(this.i!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.i);this.i=g;this.j=h;this.i===2&&this.H();this.B()};b.prototype.H=function(){var g=this;e(function(){if(g.C()){var h=fa.console;typeof h!=="undefined"&&h.error(g.j)}},1)};b.prototype.C=
function(){if(this.v)return!1;var g=fa.CustomEvent,h=fa.Event,k=fa.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=fa.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return k(g)};b.prototype.B=function(){if(this.h!=null){for(var g=0;g<this.h.length;++g)f.i(this.h[g]);this.h=null}};var f=new c;
b.prototype.I=function(g){var h=this.l();g.R(h.resolve,h.reject)};b.prototype.J=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(x,A){return typeof x=="function"?function(B){try{l(x(B))}catch(D){n(D)}}:A}var l,n,v=new b(function(x,A){l=x;n=A});this.R(k(g,l),k(h,n));return v};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.R=function(g,h){function k(){switch(l.i){case 1:g(l.j);break;case 2:h(l.j);break;
default:throw Error("Unexpected state: "+l.i);}}var l=this;this.h==null?f.i(k):this.h.push(k);this.v=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=q(g),n=l.next();!n.done;n=l.next())d(n.value).R(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(l,n){function v(B){return function(D){x[B]=D;A--;A==0&&l(x)}}var x=[],A=0;do x.push(void 0),A++,d(k.value).R(v(x.length-1),n),k=h.next();while(!k.done)})};
return b});m("Object.setPrototypeOf",function(a){return a||la});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var za=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};m("Object.assign",function(a){return a||za});
m("WeakMap",function(a){function b(k){this.h=(h+=Math.random()+1).toString();if(k){k=q(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!u(k,g)){var l=new c;da(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
n=new a([[k,2],[l,3]]);if(n.get(k)!=2||n.get(l)!=3)return!1;n.delete(k);n.set(l,4);return!n.has(k)&&n.get(l)==4}catch(v){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.h]=l;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.h]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.h)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.h)?delete k[g][this.h]:!1};return b});
m("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var l=h[1];return xa(function(){if(l){for(;l.head!=h[1];)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var n=h[0][l];if(n&&u(h[0],l))for(h=0;h<n.length;h++){var v=n[h];if(k!==k&&v.key!==v.key||k===v.key)return{id:l,list:n,index:h,entry:v}}return{id:l,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=l.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!l.next().done?!1:!0}catch(v){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},l.list.push(l.entry),this[1].previous.next=l.entry,this[1].previous=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
m("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});m("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
m("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});m("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});m("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});m("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});m("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
m("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});m("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
m("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function Aa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}m("Array.prototype.entries",function(a){return a?a:function(){return Aa(this,function(b,c){return[b,c]})}});m("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
m("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});m("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ba=this||self;function Ca(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=Ba,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Da(a){return a};var Ea=Ca(610401301,!1),Fa=Ca(748402147,!0);function Ga(){return typeof BigInt==="function"};function Ha(a){a.da=!0;return a};var Ia=Ha(function(a){return typeof a==="number"}),Ja=Ha(function(a){return typeof a==="string"}),Ka=Ha(function(a){return typeof a==="boolean"});var La=typeof Ba.BigInt==="function"&&typeof Ba.BigInt(0)==="bigint";function Ma(a){var b=a;if(Ja(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ia(b)&&!Number.isSafeInteger(b))throw Error(String(b));return La?BigInt(a):a=Ka(a)?a?"1":"0":Ja(a)?a.trim()||"0":String(a)}var Sa=Ha(function(a){return La?a>=Na&&a<=Oa:a[0]==="-"?Pa(a,Qa):Pa(a,Ra)}),Qa=Number.MIN_SAFE_INTEGER.toString(),Na=La?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ra=Number.MAX_SAFE_INTEGER.toString(),Oa=La?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Pa(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ta=typeof Uint8Array.prototype.slice==="function",w=0,y=0,Ua;function Va(a){var b=a>>>0;w=b;y=(a-b)/4294967296>>>0}function Wa(a){if(a<0){Va(-a);var b=q(Xa(w,y));a=b.next().value;b=b.next().value;w=a>>>0;y=b>>>0}else Va(a)}function Ya(a){var b=Ua||(Ua=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;w=b.getUint32(0,!0)}function Za(a){var b=Ua||(Ua=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);w=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function $a(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:ab(a,b)}function bb(a,b){return Ma(Ga()?BigInt.asUintN(64,(BigInt(b>>>0)<<BigInt(32))+BigInt(a>>>0)):ab(a,b))}function cb(a,b){return Ga()?Ma(BigInt.asIntN(64,(BigInt.asUintN(32,BigInt(b))<<BigInt(32))+BigInt.asUintN(32,BigInt(a)))):Ma(db(a,b))}
function ab(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Ga()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+eb(c)+eb(a));return c}function eb(a){a=String(a);return"0000000".slice(a.length)+a}
function db(a,b){b&2147483648?Ga()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Xa(a,b)),a=b.next().value,b=b.next().value,a="-"+ab(a,b)):a=ab(a,b);return a}
function fb(a){if(a.length<16)Wa(Number(a));else if(Ga())a=BigInt(a),w=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=w=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,w=w*1E6+d,w>=4294967296&&(y+=Math.trunc(w/4294967296),y>>>=0,w>>>=0);b&&(b=q(Xa(w,y)),a=b.next().value,b=b.next().value,w=a,y=b)}}function Xa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function gb(a,b){this.i=a>>>0;this.h=b>>>0}function hb(a){return a.i===0?new gb(0,1+~a.h):new gb(~a.i+1,~a.h)}function ib(a){if(!a)return kb||(kb=new gb(0,0));if(!/^\d+$/.test(a))return null;fb(a);return new gb(w,y)}function lb(a){return new gb(a&4294967295,Math.floor(a/4294967296))}var kb;function mb(a,b){this.i=a>>>0;this.h=b>>>0}function nb(a){if(!a)return ob||(ob=new mb(0,0));if(!/^-?\d+$/.test(a))return null;fb(a);return new mb(w,y)}
function pb(a){return new mb(a&4294967295,Math.floor(a/4294967296))}var ob,qb,rb,sb,tb,ub,vb,wb;function xb(a,b,c){if(typeof BigInt64Array!=="undefined")return vb||(vb=new BigInt64Array(1),wb=new Uint32Array(vb.buffer),vb[0]=BigInt(1),ub=wb[0]===1),vb[0]=a,a=ub?0:1,new b(wb[a],wb[1-a]);tb||(qb=BigInt(Number.MIN_SAFE_INTEGER),rb=BigInt(Number.MAX_SAFE_INTEGER),sb=BigInt(4294967295),tb=BigInt(32));if(a>=qb&&a<=rb)return c(Number(a));a=BigInt.asUintN(64,a);return new b(Number(a&sb),Number(a>>tb))};function yb(){throw Error("Invalid UTF8");}function zb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var Ab=void 0,Bb,Cb=typeof TextDecoder!=="undefined",Db,Eb=typeof String.prototype.isWellFormed==="function",Fb=typeof TextEncoder!=="undefined";
function Gb(a){var b=!1;b=b===void 0?!1:b;if(Fb){if(b&&(Eb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(Db||(Db=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function Hb(a){Ba.setTimeout(function(){throw a;},0)};function Ib(){var a=Ba.navigator;return a&&(a=a.userAgent)?a:""}var Jb,Kb=Ba.navigator;Jb=Kb?Kb.userAgentData||null:null;var Lb={},Mb=null;function Nb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Ob(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Ob(a,b){function c(k){for(;d<a.length;){var l=a.charAt(d++),n=Mb[l];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(l))throw Error("Unknown base64 encoding at char: "+l);}return k}Pb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Pb(){if(!Mb){Mb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));Lb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];Mb[f]===void 0&&(Mb[f]=e)}}}};var Qb=typeof Uint8Array!=="undefined",Rb=!(Ea&&Jb&&Jb.brands.length>0?0:Ib().indexOf("Trident")!=-1||Ib().indexOf("MSIE")!=-1)&&typeof btoa==="function",Sb=/[-_.]/g,Ub={"-":"+",_:"/",".":"="};function Vb(a){return Ub[a]||""}function Wb(a){if(!Rb)return Nb(a);a=Sb.test(a)?a.replace(Sb,Vb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Xb={};function Yb(a,b){Zb(b);this.h=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function $b(){return ac||(ac=new Yb(null,Xb))}function bc(a){Zb(Xb);var b=a.h;b=b==null||Qb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Wb(b):null;return b==null?b:a.h=b}var ac;function Zb(a){if(a!==Xb)throw Error("illegal external caller");};function cc(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.h=b}
function dc(a,b){if(typeof a==="string")return new cc(Wb(a),b);if(Array.isArray(a))return new cc(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new cc(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new cc(a,!1);if(a.constructor===Yb)return b=bc(a)||new Uint8Array(0),new cc(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new cc(a,!1);throw Error();};function ec(a,b,c,d){this.i=null;this.o=!1;this.h=this.j=this.l=0;this.init(a,b,c,d)}ec.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.T;e=e.V;e=e===void 0?!1:e;this.T=d===void 0?!1:d;this.V=e;a&&(a=dc(a,this.V),this.i=a.buffer,this.o=a.h,this.l=b||0,this.j=c!==void 0?this.l+c:this.i.length,this.h=this.l)};ec.prototype.clear=function(){this.i=null;this.o=!1;this.h=this.j=this.l=0;this.T=!1};
function fc(a,b){var c=0,d=0,e=0,f=a.i,g=a.h;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;hc(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function hc(a,b){a.h=b;if(b>a.j)throw Error();}
function ic(a){var b=a.i,c=a.h,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();hc(a,c);return e}function jc(a){return ic(a)>>>0}function kc(a){a=jc(a);return a>>>1^-(a&1)}function lc(a){return fc(a,cb)}function mc(a){var b=a.i,c=a.h,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];hc(a,a.h+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function nc(a){var b=mc(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function oc(a){var b=mc(a),c=mc(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function pc(a){for(var b=0,c=a.h,d=c+10,e=a.i;c<d;){var f=e[c++];b|=f;if((f&128)===0)return hc(a,c),!!(b&127)}throw Error();}
function qc(a){return ic(a)}function rc(a,b){if(b<0)throw Error();var c=a.h;b=c+b;if(b>a.j)throw Error();a.h=b;return c}function sc(a,b){if(b==0)return $b();var c=rc(a,b);a.T&&a.o?c=a.i.subarray(c,c+b):(a=a.i,b=c+b,c=c===b?new Uint8Array(0):Ta?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?$b():new Yb(c,Xb)}var tc=[],uc=void 0;function vc(){this.h=[]}vc.prototype.length=function(){return this.h.length};vc.prototype.end=function(){var a=this.h;this.h=[];return a};function wc(a,b,c){for(;c>0||b>127;)a.h.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.h.push(b)}function xc(a,b){for(;b>127;)a.h.push(b&127|128),b>>>=7;a.h.push(b)}function yc(a,b){if(b>=0)xc(a,b);else{for(var c=0;c<9;c++)a.h.push(b&127|128),b>>=7;a.h.push(1)}}function z(a,b){a.h.push(b>>>0&255);a.h.push(b>>>8&255);a.h.push(b>>>16&255);a.h.push(b>>>24&255)};var zc=0;function Ac(a,b,c,d){if(tc.length){var e=tc.pop();e.init(a,b,c,d);a=e}else a=new ec(a,b,c,d);this.h=a;this.l=this.h.h;this.i=this.j=-1;this.setOptions(d)}Ac.prototype.setOptions=function(a){a=(a===void 0?{}:a).X;this.X=a===void 0?!1:a};function Bc(a,b,c,d){if(Cc.length){var e=Cc.pop();e.setOptions(d);e.h.init(a,b,c,d);return e}return new Ac(a,b,c,d)}function Dc(a){a.h.clear();a.j=-1;a.i=-1;Cc.length<100&&Cc.push(a)}
function Ec(a){var b=a.h;if(b.h==b.j)return!1;a.l=a.h.h;var c=jc(a.h);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.j=b;a.i=c;return!0}function Fc(){if(zc>=100)throw new SyntaxError;zc++}
function Gc(a){try{switch(a.i){case 0:a.i!=0?Gc(a):pc(a.h);break;case 1:var b=a.h;hc(b,b.h+8);break;case 2:if(a.i!=2)Gc(a);else{var c=jc(a.h),d=a.h;hc(d,d.h+c)}break;case 5:var e=a.h;hc(e,e.h+4);break;case 3:Fc();var f=a.j;try{do{if(!Ec(a))throw Error();if(a.i==4){if(a.j!=f)throw Error();break}Gc(a)}while(1)}catch(g){if(g instanceof RangeError)throw new SyntaxError;throw g;}finally{zc>0&&zc--}break;default:throw Error();}}catch(g){if(g instanceof RangeError)throw new SyntaxError;throw g;}}
function Hc(a,b,c){var d=a.h.j,e=jc(a.h);e=a.h.h+e;var f=e-d;f<=0&&(a.h.j=e,c(b,a,void 0,void 0,void 0),f=e-a.h.h);if(f)throw Error();a.h.h=e;a.h.j=d;return b}
function Ic(a){var b=jc(a.h);a=a.h;var c=rc(a,b);a=a.i;if(Cb){var d=a,e;(e=Bb)||(e=Bb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(l){if(Ab===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),Ab=!0}catch(n){Ab=!1}}!Ab&&(Bb=void 0);throw l;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?yb():(k=a[f++],h<194||(k&192)!==128?(f--,yb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?yb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,yb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?yb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,yb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):yb(),c.length>=8192&&(g=zb(g,c),c.length=0);f=zb(g,c)}return f}function Jc(a){var b=jc(a.h);return sc(a.h,b)}
function Kc(a,b,c){var d=jc(a.h);for(d=a.h.h+d;a.h.h<d;)c.push(b(a.h))}var Cc=[];function Lc(){this.j=[];this.i=0;this.h=new vc}function Mc(a,b){b.length!==0&&(a.j.push(b),a.i+=b.length)}function Nc(a,b){C(a,b,2);b=a.h.end();Mc(a,b);b.push(a.i);return b}function Oc(a,b){var c=b.pop();for(c=a.i+a.h.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.i++;b.push(c);a.i++}function C(a,b,c){xc(a.h,b*8+c)}function Pc(a,b,c){c!=null&&(c=parseInt(c,10),C(a,b,0),yc(a.h,c))}function Qc(a,b,c){C(a,b,2);xc(a.h,c.length);Mc(a,a.h.end());Mc(a,c)}
function Rc(a,b,c,d){c!=null&&(b=Nc(a,b),d(c,a),Oc(a,b))}function Sc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?ib(a.substring(1)):ib(a)}};var Tc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Uc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Vc=Uc("jas",void 0,!0),Wc=Uc(void 0,"1oa"),Xc=Uc(void 0,Symbol()),Yc=Uc(void 0,"0ubs"),Zc=Uc(void 0,"0ubsb"),$c=Uc(void 0,"0actk"),ad=Uc("m_m","ea",!0);var bd={ca:{value:0,configurable:!0,writable:!0,enumerable:!1}},cd=Object.defineProperties,E=Tc?Vc:"ca",dd,ed=[];F(ed,7);dd=Object.freeze(ed);function fd(a,b){Tc||E in a||cd(a,bd);a[E]|=b}function F(a,b){Tc||E in a||cd(a,bd);a[E]=b}function gd(a){fd(a,8192);return a};var hd={};function id(a,b){return b===void 0?a.h!==jd&&!!(2&(a.m[E]|0)):!!(2&b)&&a.h!==jd}var jd={};function kd(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var ld={};function qd(a){return a&128?ld:void 0};function rd(a){return a};var sd=void 0;function td(a,b){if(a!=null){var c;var d=(c=sd)!=null?c:sd={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",Hb(a))}};function ud(a){return Array.prototype.slice.call(a)};var vd=typeof BigInt==="function"?BigInt.asIntN:void 0,wd=typeof BigInt==="function"?BigInt.asUintN:void 0,xd=Number.isSafeInteger,yd=Number.isFinite,zd=Math.trunc;function Ad(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function Bd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function Cd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var Dd=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function Ed(a){switch(typeof a){case "bigint":return!0;case "number":return yd(a);case "string":return Dd.test(a);default:return!1}}function Fd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return yd(a)?a|0:void 0}
function Gd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return yd(a)?a>>>0:void 0}
function Hd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(vd(64,a));if(Ed(a)){if(b==="string")return b=zd(Number(a)),xd(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(fb(a),a=db(w,y))),a;if(b==="number"){a=zd(a);if(!xd(a)){Wa(a);b=w;var c=y;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);b=$a(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}}}
function Id(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(wd(64,a));if(Ed(a)){if(b==="string")return b=zd(Number(a)),xd(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(fb(a),a=ab(w,y))),a;if(b==="number")return a=zd(a),a>=0&&xd(a)||(Wa(a),a=$a(w,y)),a}}function Jd(a){if(a==null||typeof a=="string"||a instanceof Yb)return a}
function Kd(a){if(a!=null&&typeof a!=="string")throw Error();return a}function Ld(a){return a==null||typeof a==="string"?a:void 0};function Md(a){var b=Da(Xc);return b?a[b]:void 0}function Nd(){}function Od(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Pd(a){var b=new Nd;Od(a,function(c,d,e){b[d]=ud(e)});b.h=a.h;return b}function Qd(a,b){b<100||td(Yc,1)};function Rd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Da(Xc),g;!e&&Tc&&f&&(g=a[f])&&Od(g,Qd);f=[];var h=a.length;g=4294967295;var k=!1,l=!!(b&64),n=l?b&128?0:-1:void 0;if(!(b&1)){var v=h&&a[h-1];v!=null&&typeof v==="object"&&v.constructor===Object?(h--,g=h):v=void 0;if(l&&!(b&128)&&!e){k=!0;var x;g=((x=Sd)!=null?x:rd)(g-n,n,a,v,void 0)+n}}b=void 0;for(x=0;x<h;x++){var A=a[x];if(A!=null&&(A=c(A,d))!=null)if(l&&x>=g){var B=x-n,D=void 0;((D=b)!=null?D:b={})[B]=A}else f[x]=A}if(v)for(var H in v)h=v[H],h!=
null&&(h=c(h,d))!=null&&(x=+H,A=void 0,l&&!Number.isNaN(x)&&(A=x+n)<g?f[A]=h:(x=void 0,((x=b)!=null?x:b={})[H]=h));b&&(k?f.push(b):f[g]=b);e&&Da(Xc)&&(a=Md(a))&&a instanceof Nd&&(f[Xc]=Pd(a));return f}
function Td(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Sa(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[E]|0;return a.length===0&&b&1?void 0:Rd(a,b,Td)}if(a!=null&&a[ad]===hd)return Ud(a);if(a instanceof Yb){b=a.h;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Rb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):
b);b=btoa(c)}else{c===void 0&&(c=0);Pb();c=Lb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],l=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|l>>6];l=c[l&63];d[g++]=n+h+k+l}n=0;l=e;switch(b.length-f){case 2:n=b[f+1],l=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+l+e}b=d.join("")}a=a.h=b}return a}return}return a}var Sd;function Ud(a){a=a.m;return Rd(a,a[E]|0,Td)};var Vd,Wd;function Xd(a){switch(typeof a){case "boolean":return Vd||(Vd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Wd||(Wd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Yd(a,b){return G(a,b[0],b[1])}
function G(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[E]|0;if(Fa&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Zd();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&F(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}F(a,e|64|d);return a}function Zd(){if(Fa)throw Error("carr");td($c,5)};function $d(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[E]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=ae(a,c,!1,b&&!(c&16)):(fd(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[ad]===hd)return b=a.m,c=b[E]|0,id(a,c)?a:be(a,b,c)?ce(a,b):ae(b,c);if(a instanceof Yb)return a}function ce(a,b,c){a=new a.constructor(b);c&&(a.h=jd);a.i=jd;return a}function ae(a,b,c,d){d!=null||(d=!!(34&b));a=Rd(a,b,$d,d);d=32;c&&(d|=2);b=b&16769217|d;F(a,b);return a}
function de(a){if(a.h!==jd)return!1;var b=a.m;b=ae(b,b[E]|0);fd(b,2048);a.m=b;a.h=void 0;a.i=void 0;return!0}function ee(a){if(!de(a)&&id(a,a.m[E]|0))throw Error();}function fe(a,b){b===void 0&&(b=a[E]|0);b&32&&!(b&4096)&&F(a,b|4096)}function be(a,b,c){return c&2?!0:c&32&&!(c&4096)?(F(b,c|2),a.h=jd,!0):!1};function ge(a,b,c){a=he(a.m,b,void 0,c);if(a!==null)return a}function he(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function ie(a,b,c){ee(a);var d=a.m;I(d,d[E]|0,b,c);return a}
function I(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[E]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function je(a,b){return ke(a,a[E]|0,b)}function le(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function me(a){return a==null?a:typeof a==="string"?a?new Yb(a,Xb):$b():a.constructor===Yb?a:Qb&&a!=null&&a instanceof Uint8Array?a.length?new Yb(new Uint8Array(a),Xb):$b():void 0}function ke(a,b,c){if(b&2)throw Error();var d=qd(b);var e=he(a,c,d);e=Array.isArray(e)?e:dd;var f=e===dd?7:e[E]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||le(g)||16&g)g===f||le(g)||F(e,g),e=ud(e),f=0,g=ne(g,b),I(a,b,c,e,d);g&=-13;g!==f&&F(e,g);return e}
function oe(a,b,c,d){ee(a);var e=a.m,f=e[E]|0;if(d==null){var g=pe(e);if(qe(g,e,f,c)===b)g.set(c,0);else return a}else f=re(e,f,c,b);I(e,f,b,d);return a}function se(a,b,c,d){var e=a[E]|0,f=qd(e);e=re(a,e,c,b,f);I(a,e,b,d,f)}function pe(a){if(Tc){var b;return(b=a[Wc])!=null?b:a[Wc]=new Map}if(Wc in a)return a[Wc];b=new Map;Object.defineProperty(a,Wc,{value:b});return b}function re(a,b,c,d,e){var f=pe(a),g=qe(f,a,b,c,e);g!==d&&(g&&(b=I(a,b,g,void 0,e)),f.set(c,d));return b}
function qe(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];he(b,h,e)!=null&&(f!==0&&(c=I(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function te(a,b,c){var d=a[E]|0,e=qd(d),f=he(a,c,e);if(f!=null&&f[ad]===hd){if(!id(f))return de(f),f.m;var g=f.m}else Array.isArray(f)&&(g=f);if(g){var h=g[E]|0;h&2&&(g=ae(g,h))}g=Yd(g,b);g!==f&&I(a,d,c,g,e);return g}
function ue(a,b){var c=ve,d=!1,e=he(a,4,void 0,function(f){if(f!=null&&f[ad]===hd)var g=f;else if(Array.isArray(f)){g=f[E]|0;var h=g|b&32;h|=b&2;h!==g&&F(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!id(e)&&fe(a,b),e}function we(a){var b=a.m,c=b[E]|0,d=ue(b,c);if(d==null)return d;c=b[E]|0;if(!id(a,c)){var e=d;var f=e.m,g=f[E]|0;e=id(e,g)?be(e,f,g)?ce(e,f,!0):new e.constructor(ae(f,g,!1)):e;e!==d&&(de(a)&&(b=a.m,c=b[E]|0),d=e,c=I(b,c,4,d),fe(b,c))}return d}
function xe(a){a==null&&(a=void 0);return a}function ye(a,b,c){c=xe(c);ie(a,b,c);c&&!id(c)&&fe(a.m);return a}function ze(a,b){ee(a);var c=a.m,d=c[E]|0;if(b==null)return I(c,d,1),a;for(var e=b===dd?7:b[E]|0,f=e,g=le(e),h=g||Object.isFrozen(b),k=!0,l=!0,n=0;n<b.length;n++){var v=b[n];g||(v=id(v),k&&(k=!v),l&&(l=v))}g||(e=k?13:5,e=l?e&-4097:e|4096);h&&e===f||(b=ud(b),f=0,e=ne(e,d));e!==f&&F(b,e);d=I(c,d,1,b);2&e||!(4096&e||16&e)||fe(c,d);return a}function ne(a,b){return a=(2&b?a|2:a&-3)&-273};function J(a,b,c){this.m=G(a,b,c,2048)}J.prototype.toJSON=function(){var a=Ud(this);return a};J.prototype[ad]=hd;J.prototype.toString=function(){return this.m.toString()};function K(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var Ae=K(),Be=K(),Ce=K(),De=K(),Ee=K(),Fe=K(),Ge=K(),He=K(),Ie=K(),Je=K();function Ke(a,b,c){this.h=a;this.i=b;a=Da(Ae);this.j=!!a&&c===a||!1}function Le(a,b){var c=c===void 0?Ae:c;return new Ke(a,b,c)}function Me(a,b,c,d,e){Rc(a,c,Ne(b,d),e)}var Oe=Le(function(a,b,c,d,e){if(a.i!==2)return!1;Hc(a,te(b,d,c),e);return!0},Me),Pe=Le(function(a,b,c,d,e){if(a.i!==2)return!1;Hc(a,te(b,d,c),e);return!0},Me),Qe=Symbol(),Re=Symbol(),Se=Symbol(),Te=Symbol(),Ue=Symbol(),Ve,We;
function Xe(a,b,c,d){var e=d[a];if(e)return e;e={};e.ba=d;e.P=Xd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.U=f,f=d[++g],typeof f==="function"&&(e.Z=!0,Ve!=null||(Ve=f),We!=null||(We=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var l=void 0;if(f instanceof Ke)var n=f;else n=Oe,g--;f=void 0;if((f=n)==null?0:f.j){f=d[++g];l=d;var v=g;typeof f===
"function"&&(f=f(),l[v]=f);l=f}f=d[++g];v=k+1;typeof f==="number"&&f<0&&(v-=f,f=d[++g]);for(;k<v;k++){var x=h[k];l?c(e,k,n,l,x):b(e,k,n,x)}}return d[a]=e}function Ye(a){return Array.isArray(a)?a[0]instanceof Ke?a:[Pe,a]:[a,void 0]}function Ne(a,b){if(a instanceof J)return a.m;if(Array.isArray(a))return Yd(a,b)};function Ze(a,b,c,d){var e=c.h;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function $e(a,b,c,d,e){var f=c.h,g,h;a[b]=function(k,l,n){return f(k,l,n,h||(h=Xe(Re,Ze,$e,d).P),g||(g=af(d)),e)}}
function af(a){var b=a[Se];if(b!=null)return b;var c=Xe(Re,Ze,$e,a);b=c.Z?function(d,e){return Ve(d,e,c)}:function(d,e){a:{Fc();try{for(;Ec(e)&&e.i!=4;){var f=e.j,g=c[f];if(g==null){var h=c.U;if(h){var k=h[f];if(k){var l=bf(k);l!=null&&(g=c[f]=l)}}}if(g==null||!g(e,d,f)){var n=e,v=n.l;Gc(n);if(n.X)var x=void 0;else{var A=n.h.h-v;n.h.h=v;x=sc(n.h,A)}var B=n=void 0,D=void 0,H=d,aa=f,U=x;U&&((n=(B=(D=H[Xc])!=null?D:H[Xc]=new Nd)[aa])!=null?n:B[aa]=[]).push(U)}}var ya=Md(d);ya&&(ya.h=c.ba[Ue]);var jb=
!0;break a}catch(Tb){if(Tb instanceof RangeError)throw new SyntaxError;throw Tb;}finally{zc>0&&zc--}jb=void 0}return jb};a[Se]=b;a[Ue]=cf.bind(a);return b}
function cf(a,b,c,d){var e=this[Re],f=this[Se],g=Yd(void 0,e.P),h=Md(a);if(h){var k=!1,l=e.U;if(l){e=function(B,D,H){if(H.length!==0)if(l[D]){B=q(H);D=B.next();var aa;try{for(;!D.done;D=B.next()){var U=Bc(D.value);try{k=!0,f(g,U)}finally{Dc(U)}}}finally{D&&!D.done&&(aa=B.return)&&aa.call(B)}}else d==null||d(a,D,H)};if(b==null)Od(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var v=a[E]|0;if(v&2&&v&2048&&(c==null||!c.ga))throw Error();var x=qd(v),A=function(B,D){if(he(a,B,x)!=null)switch(c==null?
void 0:c.fa){case 1:return;default:throw Error();}D!=null&&(v=I(a,v,B,D,x));delete h[B]};b==null?kd(g,g[E]|0,function(B,D){A(B,D)}):A(b,he(g,b,x))}}}}function bf(a){a=Ye(a);var b=a[0].h;if(a=a[1]){var c=af(a),d=Xe(Re,Ze,$e,a).P;return function(e,f,g){return b(e,f,g,d,c)}}return b};function df(a,b,c){a[b]=c.i}function ef(a,b,c,d){var e,f,g=c.i;a[b]=function(h,k,l){return g(h,k,l,f||(f=Xe(Qe,df,ef,d).P),e||(e=ff(d)))}}function ff(a){var b=a[Te];if(!b){var c=Xe(Qe,df,ef,a);b=function(d,e){return gf(d,e,c)};a[Te]=b}return b}function gf(a,b,c){kd(a,a[E]|0,function(d,e){if(e!=null){var f=hf(c,d);f?f(b,e,d):d<500||td(Zc,3)}});(a=Md(a))&&Od(a,function(d,e,f){Mc(b,b.h.end());for(d=0;d<f.length;d++)Mc(b,bc(f[d])||new Uint8Array(0))})}
function hf(a,b){var c=a[b];if(c)return c;if(c=a.U)if(c=c[b]){c=Ye(c);var d=c[0].i;if(c=c[1]){var e=ff(c),f=Xe(Qe,df,ef,c).P;c=a.Z?We(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function L(a,b,c){if(Array.isArray(b)){var d=b[E]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&F(b,a);c&&a&2&&Object.freeze(b);return b}}function M(a,b,c){return new Ke(a,b,c)}function N(a,b,c){return new Ke(a,b,c)}function O(a,b,c){I(a,a[E]|0,b,c,qd(a[E]|0))}
var jf=Le(function(a,b,c,d,e){if(a.i!==2)return!1;a=Hc(a,Yd([void 0,void 0],d),e);a=ud(a);d=b[E]|0;e=qd(d);if(d&2)throw Error();var f=he(b,c,e);if(Array.isArray(f)){var g=f[E]|0;g&8192||F(f,g|=8192);if(g&2){f=ud(f);for(g=0;g<f.length;g++){var h=f[g]=ud(f[g]);if(Array.isArray(h[1])){var k=h[1];fd(k,34);h[1]=k}}f=gd(f);I(b,d,c,f,e)}f.push(a)}else I(b,d,c,gd([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Rc(a,c,Yd(g,d),e)}gd(b)}});
function kf(a,b,c){b=Bd(b);b!=null&&(C(a,c,1),a=a.h,Za(b),z(a,w),z(a,y))}function lf(a,b,c){b=Bd(b);b!=null&&(C(a,c,5),a=a.h,Ya(b),z(a,w))}function mf(a,b,c){b=Hd(b);if(b!=null){switch(typeof b){case "string":nb(b)}if(b!=null)switch(C(a,c,0),typeof b){case "number":a=a.h;Wa(b);wc(a,w,y);break;case "bigint":c=xb(b,mb,pb);wc(a.h,c.i,c.h);break;default:c=nb(b),wc(a.h,c.i,c.h)}}}
function nf(a,b,c){b=Id(b);if(b!=null){switch(typeof b){case "string":ib(b)}if(b!=null)switch(C(a,c,0),typeof b){case "number":a=a.h;Wa(b);wc(a,w,y);break;case "bigint":c=xb(b,gb,lb);wc(a.h,c.i,c.h);break;default:c=ib(b),wc(a.h,c.i,c.h)}}}function of(a,b,c){b=Fd(b);b!=null&&b!=null&&(C(a,c,0),yc(a.h,b))}function pf(a,b,c){b=Cd(b);b!=null&&(C(a,c,0),a.h.h.push(b?1:0))}function qf(a,b,c){b=Ld(b);b!=null&&Qc(a,c,Gb(b))}function rf(a,b,c,d,e){Rc(a,c,Ne(b,d),e)}function sf(a,b,c){Pc(a,c,Fd(b))}
function tf(a,b,c){if(a.i!==5&&a.i!==2)return!1;b=je(b,c);a.i==2?Kc(a,nc,b):b.push(nc(a.h));return!0}function uf(a,b,c){if(a.i!==0)return!1;O(b,c,fc(a.h,bb));return!0}function vf(a,b,c){if(a.i!==0&&a.i!==2)return!1;b=je(b,c);a.i==2?Kc(a,ic,b):b.push(ic(a.h));return!0}function wf(a,b,c){if(a.i!==0&&a.i!==2)return!1;b=je(b,c);a.i==2?Kc(a,pc,b):b.push(pc(a.h));return!0}
var xf=M(function(a,b,c){if(a.i!==1)return!1;O(b,c,oc(a.h));return!0},kf,He),yf=M(function(a,b,c,d){if(a.i!==1)return!1;se(b,c,d,oc(a.h));return!0},kf,He),P=M(function(a,b,c){if(a.i!==5)return!1;O(b,c,nc(a.h));return!0},lf,Ge),zf=N(tf,function(a,b,c){b=L(Bd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(C(e,f,5),e=e.h,Ya(g),z(e,w))}},Ge),Af=N(tf,function(a,b,c){b=L(Bd,b,!0);if(b!=null&&b.length)for(C(a,c,2),xc(a.h,b.length*4),c=0;c<b.length;c++){var d=a.h;Ya(b[c]);z(d,w)}},
Ge),Bf=M(function(a,b,c,d){if(a.i!==5)return!1;se(b,c,d,nc(a.h));return!0},lf,Ge),Cf=M(function(a,b,c){a.i!==0?a=!1:(O(b,c,lc(a.h)),a=!0);return a},mf,Ee),Df=N(function(a,b,c){a.i!==0&&a.i!==2?a=!1:(b=je(b,c),a.i==2?Kc(a,lc,b):b.push(lc(a.h)),a=!0);return a},function(a,b,c){b=L(Hd,b,!1);if(b!=null&&b.length){c=Nc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.h;Wa(e);wc(f,w,y);break;case "bigint":e=xb(e,mb,pb);wc(a.h,e.i,e.h);break;default:e=nb(e),wc(a.h,e.i,e.h)}}Oc(a,
c)}},Ee),Ef=M(function(a,b,c,d){a.i!==0?a=!1:(se(b,c,d,lc(a.h)),a=!0);return a},mf,Ee),Ff=M(function(a,b,c){return uf(a,b,c)},nf,Fe),Gf=M(function(a,b,c){return uf(a,b,c)},nf,Fe),Q=M(function(a,b,c){if(a.i!==0)return!1;O(b,c,ic(a.h));return!0},of,De),Hf=N(vf,function(a,b,c){b=L(Fd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(C(e,f,0),yc(e.h,g))}},De),If=N(vf,function(a,b,c){b=L(Fd,b,!0);if(b!=null&&b.length){c=Nc(a,c);for(var d=0;d<b.length;d++)yc(a.h,b[d]);Oc(a,c)}},
De),Jf=M(function(a,b,c,d){if(a.i!==0)return!1;se(b,c,d,ic(a.h));return!0},of,De),R=M(function(a,b,c){if(a.i!==0)return!1;O(b,c,pc(a.h));return!0},pf,Be),Kf=N(wf,function(a,b,c){b=L(Cd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(C(e,f,0),e.h.h.push(g?1:0))}},Be),Lf=N(wf,function(a,b,c){b=L(Cd,b,!0);if(b!=null&&b.length)for(C(a,c,2),xc(a.h,b.length),c=0;c<b.length;c++)a.h.h.push(b[c]?1:0)},Be),Mf=M(function(a,b,c,d){if(a.i!==0)return!1;se(b,c,d,pc(a.h));return!0},pf,Be),
S=M(function(a,b,c){if(a.i!==2)return!1;O(b,c,Ic(a));return!0},qf,Ce),Nf=M(function(a,b,c,d){if(a.i!==2)return!1;se(b,c,d,Ic(a));return!0},qf,Ce),T=N(function(a,b,c){if(a.i!==2)return!1;a=Ic(a);ke(b,b[E]|0,c).push(a);return!0},function(a,b,c){b=L(Ld,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Qc(e,f,Gb(g))}},Ce),V,Of=void 0;Of=Of===void 0?Ae:Of;
V=new Ke(function(a,b,c,d,e){if(a.i!==2)return!1;d=Yd(void 0,d);ke(b,b[E]|0,c).push(d);Hc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)rf(a,b[f],c,d,e);a=b[E]|0;a&1||F(b,a|1)}},Of);
var W=Le(function(a,b,c,d,e,f){if(a.i!==2)return!1;var g=b[E]|0;re(b,g,f,c,qd(g));b=te(b,d,c);Hc(a,b,e);return!0},rf),Pf=M(function(a,b,c){if(a.i!==2)return!1;O(b,c,Jc(a));return!0},function(a,b,c){b=Jd(b);b!=null&&Qc(a,c,dc(b,!0).buffer)},Ie),X=M(function(a,b,c){if(a.i!==0)return!1;O(b,c,jc(a.h));return!0},function(a,b,c){b=Gd(b);b!=null&&b!=null&&(C(a,c,0),xc(a.h,b))},K()),Y=M(function(a,b,c){if(a.i!==0)return!1;O(b,c,ic(a.h));return!0},sf,Je),Qf=N(function(a,b,c){if(a.i!==0&&a.i!==2)return!1;b=
je(b,c);a.i==2?Kc(a,qc,b):b.push(ic(a.h));return!0},function(a,b,c){b=L(Fd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)Pc(a,c,b[d])},Je),Rf=M(function(a,b,c,d){if(a.i!==0)return!1;se(b,c,d,ic(a.h));return!0},sf,Je),Sf=N(function(a,b,c){if(a.i!==0&&a.i!==2)return!1;b=je(b,c);a.i==2?Kc(a,kc,b):b.push(kc(a.h));return!0},function(a,b,c){b=L(Fd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(C(e,f,0),xc(e.h,(g<<1^g>>31)>>>0))}},K()),Tf=[!0,S,Q],Uf=[!0,S,R],Vf=[!0,S,S];function Wf(a){return function(b){var c=new Lc;gf(b.m,c,Xe(Qe,df,ef,a));Mc(c,c.h.end());b=new Uint8Array(c.i);for(var d=c.j,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.j=[b];return b}};var Xf=[0,M(function(a,b,c){if(a.i!==1)b=!1;else{var d=a.h;a=mc(d);d=mc(d);O(b,c,bb(a,d));b=!0}return b},function(a,b,c){b=Id(b);if(b!=null)switch(Sc(b),C(a,c,1),a=a.h,Sc(b),typeof b){case "number":b<0?(c=hb(lb(-b)),b=c.h,z(a,c.i),z(a,b)):(Va(b),z(a,w),z(a,y));break;case "bigint":c=b<BigInt(0)?hb(xb(-b,gb,lb)):xb(b,gb,lb);b=c.h;z(a,c.i);z(a,b);break;default:c=b.length&&b[0]==="-"?hb(ib(b.substring(1))):ib(b),b=c.h,z(a,c.i),z(a,b)}},K()),-1];var Yf=[0,M(function(a,b,c){if(a.i!==5)return!1;a=a.h;var d=a.i,e=a.h,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];hc(a,a.h+4);O(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=Fd(b);b!=null&&(C(a,c,5),a=a.h,a.h.push(b>>>0&255),a.h.push(b>>>8&255),a.h.push(b>>>16&255),a.h.push(b>>>24&255))},K()),-1];var Zf=[0,Y,-1,Cf,S,Yf,-1,P,Q,Y,Xf,S,Y,-1,[0,Yf,-1],Q,Gf,Xf,P,[0,1,Q,-4,xf,[0,P,-1,Q],S,P,V,[0,Y,Q],Q,-1,Y,-2,P,-1,Y,P,Y,Q,[0,3,Q,-1,4,N(function(a,b,c){if(a.i!==2)return!1;a=Jc(a);ke(b,b[E]|0,c).push(a);return!0},function(a,b,c){b=L(Jd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Qc(e,f,dc(g,!0).buffer)}},Ie),Q],xf,X,[0,Y,-1,S,-1],R],S,Qf,V,[0,Xf,V,[0,S,Y],P,Y,-1],1,V,[0,Gf,-1,X],Y,Xf];var $f=[0,Cf,[0,P,S,Q,S,Q,Hf,Cf,S,Q,S,-1,P,Q,P],Pf,[0,N(function(a,b,c){if(a.i!==1&&a.i!==2)return!1;b=je(b,c);if(a.i==2){c=a.h;a=jc(a.h)/8;var d=c.h,e=8*a;if(d+e>c.j)throw Error();var f=c.i;d+=f.byteOffset;uc===void 0&&(uc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(uc)for(c.h+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(oc(c))}else b.push(oc(a.h));return!0},function(a,b,c){b=L(Bd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(C(e,f,1),e=e.h,Za(g),z(e,w),z(e,y))}},He),-1]];function ve(a){this.m=G(a,void 0,void 0,2048)}p(ve,J);function ag(a){a=ge(a,1,me);return a==null?$b():a}function bg(a){var b=16E3;b=b===void 0?0:b;a=Fd(ge(a,2));return a!=null?a:b};function cg(a){this.m=G(a,void 0,void 0,2048)}p(cg,J);function dg(a){this.m=G(a,void 0,void 0,2048)}p(dg,J);var eg=[0,Pf,Q];var fg=[0,[1,2,3,4],Nf,Rf,W,[0,S,Y],Rf];var gg=[0,S,-2,3,P,S,T,Y,-1,V,fg,S,-2];var hg=[0,Q,-3];var ig=[0,[1,2,3,4],Mf,-1,Nf,-1];var kg=[0,S,-1,1,S,-1,6,T,[0,X,S,X,Q,X,-4,P,X,P,-1],R,T,-1];var Z=[0,Y,-5];var lg=[0,[0,S,-5,R,T,Z],S,-7,R,S,T,Z];var mg=[0,T,1,Y,-1,S];var ng=[0,S,-2,Z,S];var og=[0,S,-1,R,S,T,Z];var pg=[0,V,[0,S,-1],S,R,S];var qg=[0,S,-2,Z];var rg=[0,S,-3,Q,S,R,S,-1,R,S,T,Z,S,-2];var sg=[0,R,S,-3,Q,S,R,S,T,Z];var tg=[0,S,-3,Q,S,-3,R,S,T,Z];var ug=[0,S,Q,Y,S];var vg=[0,S,-2,Q,S,R,S,R,T,Z];var wg=[0,S,-2,R];var xg=[0,sg,vg,og,S,Q,S,R,S,T,Z];var yg=[0,sg,Cf,S,Q,S,R,S,T,Z,S];var zg=[0,S,-1,R,S,T,Z,R];var Ag=[0,S,Q,R];var Bg=[0,S,T,S,Q,S,R,S,T,Z];var Cg=[0,Q,-2,R,S,Q,S,Q,S,R,S,T,Z,R];var Dg=[0,Y,-1];var Eg=[0,P,-1];var Fg=[0,V,[0,P,-2],P,-1,Q,V,[0,Q,Y,Q,Y,X,Y,-1,V,Eg,[0,P,-1],[0,V,Eg,P,Y],[0,V,Eg,Y]],P];var Gg=[0,P,-2];var Hg=[-11,{},hg,S,[0,Lf,If,Af,T,V,[0,Af],[0,Af]],Af,S,-1,[0,Gg],S,[0,Af,-1,V,[0,Y,Q]],-1];var Ig=[0,hg,[0,R,P,Af,-1],Q,[0,Af]];var Jg=[0,Q,-2];var Kg=[0,Y,[0,Hf,Df]];var Lg=[0,Y,[0,Hf,T]];var Mg=[0,Q,-1,Y,Q];var Ng=[0,Af,If];var Og=[0,Af,If,S];var Pg=[0,[0,Ff,Y,R]];var Qg=[0,Q,-2,S];var Rg=[0,Y];var Tg=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],Nf,S,W,og,W,zg,W,sg,W,vg,W,Cg,W,xg,W,rg,W,lg,W,Bg,W,yg,W,tg,W,pg,Nf,-1,V,wg,Nf,-1,Fg,Bf,[0,R,-1,Y,Dg,R,-1,P,R,T,Mg,Y,-1],Zf,R,W,[0,S,-1],V,[0,S,-1],[0,T,R],Z,Y,Rg,R,W,Ag,S,T,S,W,qg,W,ng,S,-1,R,W,ug,R,Qg,S],V,[0,S,V,[0,S,-1,Y],V,[0,S,-1],S,Y,[0,Y,-3],T,R,S],4,Rg,P,R,function(){return Sg},S,Pg,R,[0,R,-1]],Sg=[0,V,function(){return Tg},-1];var Ug=function(a,b){return function(c,d){a:{var e={V:!0};d&&Object.assign(e,d);c=Bc(c,void 0,void 0,e);try{var f=new a,g=f.m;af(b)(g,c);var h=f;break a}catch(k){if(k instanceof RangeError)throw new SyntaxError;throw k;}finally{Dc(c)}h=void 0}return h}}(dg,[0,Y,2,eg,Y,[-500,{},Gf,S,Tg,-1,1,[0,Y,Q,-1,P],[0,S,-5,Q,S,1,R,-1,S,Y,V,gg,S],Cf,-2,89,[-5,{},V,[-75,{},hg,X,-1,S,Y,S,-2,R,P,Y,S,R,-1,5,og,zg,S,sg,vg,Cg,xg,sg,rg,lg,Bg,yg,tg,S,-1,qg,S,ng,1,pg,ug,[0,S,-1],V,wg,7,kg,1,S,R,S,R,Ag,S,R,S,-2,ig,S,R,P,
T,1,S,R,1,S,mg,Y,R],V,[-71,{},hg,Y,S,-1,R,1,S,Y,kg,P,Y,R,Qf,S,Dg,1,Q,R,1,S,Y,P,[0,[0,P,-2],[0,P,-2]],[0,Y,-2],25,Fg,S,3,R,-1,1,R,S,2,R,ig,S,Y,P,S,-1,1,S],V,[-11,{},hg,S,Y,5,[0,Q,-3],S],V,[-12,{},hg,S,R,P,-1,[0,P,-6,V,[0,S,Y,P]],zf,Q,-1,S,[0,[0,Q,-3],V,[0,S,P]]]],1,[0,3,V,[0,V,Jg,Jg],R],3,Mg,Y,-1,1,[-12,{},Mg,Y,-1,[0,Y,2,Y,-1],Y,-1,S,3,[0,R,-2]],39,[0,[0,Q,-2,If,-2],Lg,-2,Kg,Lg,-2,Kg,-5],49,[-3,{},[0,V,Hg,[0,V,[0,S,V,[0,Q,P,V,[0,Q,P,-1,Q],R],V,[0,Q,P],R,-2]]],V,[0,Q,V,[0,hg,[-10,{},Q,-2,X,[0,X,-2,
P,-8,zf,-5,Sf,-1],Qf,Q,-2],Gg,P,-2,V,[0,Y,zf]]]],[-3,{},[0,V,Hg],V,[-6,{},V,Ig,V,Gg,Hf,Kf,If]],48,[0,[0,V,Ig,$f],[0,P,X,-1,P,X]],49,eg,599,[-1,{}],R,[0,P,-2,Q],[-3,{},V,[-7,{},X,-1,R,V,[0,[1,2,3,4],W,[-5,{},Y,S,-1,R],W,[0],W,[0],W,[0]],P,X],X],Ng,V,Og]]);var Vg=Wf(gg);function Wg(a){this.m=G(a,void 0,void 0,2048)}p(Wg,J);var Xg=[1,4];function Yg(a){this.m=G(a,11,void 0,2048)}p(Yg,J);var Zg=[0,Q,Pf,Y];var $g=[-11,{},[0,V,[0,Y,1,Y],Qf,Zf,T,V,[0,S,Y,P,Y],1,Y,-1,R],[0,S,-3,P,[0,Q,S],Qf,-1],[0,Xg,Bf,[0,Y],[0,2,Y],Rf,[0,R,-1],P,Y,-2],[0,1,P,V,[0,S,-1],Qf,Pg,Q],mg,[-1,{}],[0,[1,3],W,[0,[3,4],V,fg,-1,Jf,Mf,V,fg],S,Nf],[0,[1,2,3,4,5,6,7,8,9,10,11],Rf,-10],[0,[1,2],[6],[3,4,5],W,Zg,W,Ng,W,Zg,W,Ng,W,[0,Af],W,[0,Q,-1,R,P,-1,Q]],[0,[1],W,Ng,V,Og,Zg]];var ah=[-3,{},S,$g];function bh(a){this.m=G(a,void 0,void 0,2048)}p(bh,J);function ch(a){this.m=G(a,5,void 0,2048)}p(ch,J);function dh(a){this.m=G(a,void 0,void 0,2048)}p(dh,J);var eh=[2,3,4];var fh=[0,S,-2];var gh=[0,[3,4],S,-1,Ef,yf,Q,-1,S,-1];var hh=[0,eh,Q,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],Q,S,-1,$g,V,[0,[4,5],Q,S,-1,Rf,Nf,S,$g,Y],S,-1,Qg,R,90,Nf,W,[0,S,Y,[0,Y,P,Y]],W,[0,S],W,[0,S,Q],W,[0,S,Y],W,[0,S,-1],W,[0,S,Y],W,gh,W,[0,1,S],W,fh,W,[0,T,Y],W,[0,[5,6,7],Q,-2,S,Rf,-1,Jf],W,[0,[5,6],Q,-3,Rf,Jf],W,[0,[1,2],[4,5,6],W,gh,W,fh,S,Rf,-1,Jf],W,[0,[3,4],[8,9,10],Q,-1,Jf,Nf,Q,Y,S,Rf,-1,Jf],W,[0,S,T,S],W,[0,[4,5,6],gh,S,1,Rf,-1,Jf],W,[0,S,-3,Q,S,-2],W,[0,S,Y],W,[0,V,[0,S,-1],S,
R],W,[0,S,-1]],$g,V,[0,Q,-1,$g],R],W,ah,W,[0,[1,2],W,Zg,W,[0,S]]];var ih=[0,jf,Uf,jf,Tf,jf,Vf];function jh(a){this.m=G(a,4,void 0,2048)}p(jh,J);var kh=[-4,{},V,hh,$g,ih];function lh(a){this.m=G(a,3,void 0,2048)}p(lh,J);var mh=Wf([-3,{},V,Tg,kh]);function nh(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.i=!1;this.u=[];this.S={};this.N={};this.F={};this.O={};this.D={};this.aa=new TextEncoder;this.W="";this.J=null;this.K=0;this.L=[];this.I=this.v=this.B=this.l=!1;this.A=[];this.M=[];this.C=[];this.j=a;this.H=this.j.createGain()}ba=nh.prototype;
ba.init=function(a){var b=this;return t(function(c){switch(c.h){case 1:if(b.i)return c.return();b.i=!0;b.extensionId=a;return c.i(loadWasmTtsBindings(),2);case 2:return b.h=c.l,c.i(oh(b),3);case 3:return c.i(ph(b),4);case 4:return c.return(qh(b))}})};ba.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.h==1?b.i?e.G(2):e.i(b.init(b.extensionId),2):e.h!=4?(c="offscreenLanguageStatusResponse",d=a,e.i(rh(b,a),4)):e.return({type:c,lang:d,status:e.l})})};
ba.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.h==1?b.i?e.G(2):e.i(b.init(b.extensionId),2):e.h!=4?(c="offscreenLanguageStatusResponse",d=a,e.i(sh(b,a),4)):e.return({type:c,lang:d,status:e.l})})};ba.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.h==1)return b.i?d.G(2):d.i(b.init(b.extensionId),2);if(d.h!=4)return d.i(th(b,a),4);(c=d.l)&&uh(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function th(a,b){var c,d,e,f,g,h,k;return t(function(l){switch(l.h){case 1:c=vh(a,b),d=!1,e=q(c),f=e.next(),l.L(2);case 4:if(f.done){l.G(2);break}h=f.value;wh(a,h);if(!h.remote||h.unloaded){l.G(5);break}k="/voices/"+h.fileId;l.C(7);return l.i(xh(a,k),9);case 9:d=!0;l.B(5);break;case 7:l.A();case 5:f=e.next();l.G(4);break;case 2:l.J();f&&!f.done&&(g=e.return)&&g.call(e);l.K(3);break;case 3:return l.return(d)}})}
ba.onStop=function(a){var b=this,c;return t(function(d){if(!b.i)return d.return();yh(b);b.l=!1;b.B=!1;b.v=a;b.o&&(c={command:"clearBuffers"},b.o.port.postMessage(c),b.o.disconnect());for(zh(b);b.M.length>0;)window.clearTimeout(b.M.pop());b.A=[];b.L.length=0;b.J=null;b.K=0;d.D()})};ba.onPause=function(){var a=this;return t(function(b){if(b.h==1){if(!a.i)return b.return();zh(a);a.v=!0;return b.i(a.j.suspend(),2)}a.l=!1;b.D()})};
ba.onResume=function(){var a=this;return t(function(b){if(b.h==1){if(!a.i||a.l)return b.return();a.v=!1;return a.B?b.i(a.j.resume(),2):(a.C.length===0&&Ah(a),b.return(Bh(a)))}a.l=!0;Ch(a);b.D()})};
ba.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.h){case 1:return c.v=!1,k.i(c.init(c.extensionId),2);case 2:if(!c.h)throw Error("WASM module not initialized.");return b.voiceName?k.i(c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.W===d){k.G(4);break}k.C(5);return k.i(Dh(c,d,!1),7);case 7:e=c.F[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.h){var l=Eh(c,g);var n=Eh(c,f),v=c.h._GoogleTtsInit(l,
n);c.h._free(n);c.h._free(l);l=v===1}else l=!1;if(!l)throw Error("Failed to initialize pipeline "+g);k.B(4);break;case 5:return k.A(),k.return(Promise.reject(Error("Voice is not available")));case 4:c.W=d;var x=b.lang;c.extensionId&&x&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:x});try{if(x=d,c.h&&a.length){var A=new ch,B=new bh;var D=ie(B,2,Kd(a));var H=ze(A,[D]);var aa=new Wg,U=b.rate;var ya=oe(aa,1,Xg,Ad(!U||U<.1||U>10?1:U));var jb=b.pitch;l=ie(ya,6,Ad(jb?Math.pow(2,
(jb-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.H.gain.value=Math.min(Math.max(b.volume,0),1));n=new jh;v=new dh;A=H;A=xe(A);oe(v,2,eh,A);A&&!id(A)&&fe(v.m);var Tb=ze(n,[v]);var Lh=new Yg;var Mh=ye(Lh,3,l);var Nh=ye(Tb,2,Mh);var Oh=new lh;var Ph=ye(Oh,2,Nh);var md=Array.from(new Uint8Array(mh(Ph))),Qh=c.O[x],Rh=new cg;var Sh=ie(Rh,1,Kd(Qh));var nd=Vg(Sh),od=c.h._malloc(md.length);c.h.HEAPU8.set(md,od);var pd=c.h._malloc(nd.length);c.h.HEAPU8.set(nd,pd);var Th=c.h._GoogleTtsInitBuffered(od,pd,
md.length,nd.length);c.h._free(od);c.h._free(pd);if(!Th)throw Error("Failed to initialize buffered synthesis.");Ah(c)}}catch(jg){return h=jg instanceof Error?jg.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.D()}})};
function qh(a){return a.j.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.o=new AudioWorkletNode(a.j,"streaming-worklet-processor");a.o.port.onmessage=function(b){a.utterance&&!a.I&&b.data.type==="empty"&&(Fh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.H.connect(a.j.destination)})}function Eh(a,b){b=a.aa.encode(b+"\x00");var c=a.h._malloc(b.length);a.h.HEAPU8.set(b,c);return c}
function Ah(a){var b=setTimeout(function(){a.I=!0;var c=a.h,d=c._GoogleTtsReadBuffered();if(d===-1)Fh(a,{type:"error"}),yh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)Gh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=Ug(c.slice(0,
e));d=d===0;e=c.m;ue(e,e[E]|0)!==void 0?Hh(a,c,d):Ih(a,null);d?yh(a):Ah(a)}},0);a.C.push(b)}function yh(a){a.I=!1;a.h._GoogleTtsFinalizeBuffered()}function zh(a){for(;a.C.length>0;)window.clearTimeout(a.C.pop())}function Gh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.l?c<-100||(c<2?Fh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.l?Fh(a,{type:"word",charIndex:d,length:e}):a.A.push(b)},c),a.M.push(c))):a.A.push(b))}
function Ch(a){var b=a.A;a.A=[];b=q(b);var c=b.next(),d;try{for(;!c.done;c=b.next())Gh(a,c.value)}finally{c&&!c.done&&(d=b.return)&&d.call(b)}}function Hh(a,b,c){if(bg(we(b))===24E3){var d;b=(d=ag(we(b)))==null?void 0:new Uint8Array(bc(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});Jh(a,d,c)}}
function Jh(a,b,c){for(var d=a.J,e=a.K,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(Ih(a,d),e=0,d=null)}e!==0&&(c?Ih(a,d):(a.J=d,a.K=e))}function Ih(a,b){b&&a.L.push(b);if(a.o)for(;b=a.L.shift();)a.o.port.postMessage({command:"addBuffer",buffer:b}),a.B||a.v||Bh(a)}function Bh(a){return t(function(b){if(b.h==1)return a.o.connect(a.H),b.i(a.j.resume(),2);a.l=!0;a.B=!0;Fh(a,{type:"start",charIndex:0});Ch(a);b.D()})}
fa.Object.defineProperties(nh.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.u}}});function rh(a,b){return t(function(c){return c.return(Kh(a,b,!1))})}function sh(a,b){return t(function(c){return c.return(Kh(a,b,!0))})}
function Kh(a,b,c){var d,e,f;return t(function(g){switch(g.h){case 1:return d=vh(a,b),e=d.map(function(h){return Dh(a,h.speakers[0].name,c)}),g.C(2),g.i(Promise.all(e),4);case 4:f="installed";c&&uh(a);g.B(3);break;case 2:g.A(),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function vh(a,b){var c=b.toLowerCase();return c.includes("-")?a.u.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.u.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Uh(a,b,c){var d,e,f,g,h,k,l,n,v,x,A;return t(function(B){if(!a.D[b])return B.return(Promise.resolve());d=a.D[b];f=q(Object.entries(a.N));g=f.next();try{for(;!g.done;g=f.next())if(k=g.value,l=q(k),n=l.next().value,v=l.next().value,x=n,A=v,d===A){e=x;break}}finally{g&&!g.done&&(h=f.return)&&h.call(f)}return e?B.return(Dh(a,e,c)):B.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function Dh(a,b,c){var d,e,f,g,h,k;return t(function(l){switch(l.h){case 1:if(!a.h)return l.return(Promise.reject(Error("WASM module not initialized.")));l.C(2);return l.i(Uh(a,b,c),4);case 4:l.B(3);break;case 2:return d=l.A(),l.return(Promise.reject(Error(""+d)));case 3:e=a.F[b];if(!e)return l.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.h.FS.stat(g))return l.return(Promise.resolve())}catch(n){}k=a.S[b];return c||k.indexOf("http")!==
0?l.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){var v,x,A,B,D;return t(function(H){if(H.h==1)return n?H.i(Vh(a,e,n),3):H.return(Promise.reject(Error("Failed to fetch voice from url: "+k)));if(H.h!=2&&(v=H.l,!v))return H.return(Promise.reject(Error("Failed to validate voice data: "+e)));try{a.h.FS.stat(f)}catch(aa){a.h.FS.mkdir(f)}a.h.FS.stat(f);x=Eh(a,f);A=new Uint8Array(n);B=a.h._malloc(A.length);a.h.HEAPU8.set(A,
B);D=a.h._GoogleTtsInstallVoice(x,B,n.byteLength);a.h._free(x);a.h._free(B);return D!==1?H.return(Promise.reject(Error("Failed to install voice."))):H.return(new Promise(function(aa,U){a.h.FS.syncfs(!1,function(ya){ya?U(ya):aa()})}))})})):l.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function Fh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function oh(a){var b,c;return t(function(d){if(d.h==1){if((b=a.h)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.h.FS.stat("/voices")}catch(e){a.h.FS.mkdir("/voices")}d.C(2);return d.i(new Promise(function(e,f){a.h.FS.mount(a.h.IDBFS,{},"/voices");a.h.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.h!=2)return d.B(0);c=d.A();throw c;})}
function ph(a){var b,c,d;return t(function(e){switch(e.h){case 1:return e.C(2),e.i(fetch("voices.json"),4);case 4:b=e.l;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return e.i(b.json(),5);case 5:c=e.l;a.u=c;uh(a);e.B(0);break;case 2:throw d=e.A(),d;}})}
function uh(a){a.S={};a.N={};a.F={};a.O={};a.D={};var b={},c=q(a.u),d=c.next(),e;try{for(;!d.done;d=c.next()){var f=d.value,g=q(f.speakers),h=g.next(),k;try{for(;!h.done;h=g.next()){var l=h.value;a.N[l.name]=f.id;a.F[l.name]=f.fileId;a.O[l.name]=l.speaker;f.dependentVoiceId&&(a.D[l.name]=f.dependentVoiceId);wh(a,f);a.S[l.name]=f.remote&&f.unloaded?f.url:"/"+f.id+".zvoice";var n=f.id.split("-");if(n.length<2)throw Error("Unexpected voice id format: "+f.id);var v=n[0]+"-"+n[1].toUpperCase();f.language=
v;f.remote&&f.unloaded||(b[v]||(b[v]=[]),b[v].push(l.name))}}finally{h&&!h.done&&(k=g.return)&&k.call(g)}}}finally{d&&!d.done&&(e=c.return)&&e.call(c)}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function wh(a,b){try{a.h.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function xh(a,b){if(a.h)try{var c=a.h.FS.readdir(b),d=q(c),e=d.next(),f;try{for(;!e.done;e=d.next()){var g=e.value;g!=="."&&g!==".."&&a.h.FS.unlink(b+"/"+g)}}finally{e&&!e.done&&(f=d.return)&&f.call(d)}a.h.FS.rmdir(b);return new Promise(function(h,k){a.h.FS.syncfs(!1,function(l){l?k(l):h()})})}catch(h){return Promise.resolve()}}
function Vh(a,b,c){var d,e;return t(function(f){if(f.h==1)return f.i(Wh(c),2);d=f.l;if(!d)return f.return(!1);e=a.u.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Wh(a){var b,c,d,e;return t(function(f){if(f.h==1)return crypto&&crypto.subtle?f.i(crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.l;if(!b)return f.return("");c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})};var Xh=new nh,Yh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Yh||(Yh=Xh.init(b.id));Yh.then(function(){switch(a.type){case "init":Xh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Xh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Xh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Xh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":th(Xh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Xh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Xh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Xh.onPause();c({result:"Paused speech"});break;case "resume":Xh.onResume(),c({result:"Resumed speech"})}});return!0});
