-- local group = vim.api.nvim_create_augroup("InlayHintsNormalModeOnly", { clear = true })
--
-- vim.api.nvim_create_autocmd("ModeChanged", {
--     group = group,
--     pattern = "*:*",
--     desc = "Enable inlay hints only in normal mode",
--     callback = function(args)
--         local bufnr = args.buf
--         local clients = vim.lsp.get_clients({ bufnr = bufnr, method = "textDocument/inlayHint" })
--
--         if vim.api.nvim_buf_is_valid(bufnr) and #clients > 0 and next(clients) then
--             vim.lsp.inlay_hint.enable(args.match:sub(3, 3) == "n", { bufnr = bufnr })
--         end
--     end,
-- })
