local M = {}

M.kinds = {
	Array = "󰅪 ",
	Boolean = " ",
	BreakStatement = "󰙧 ",
	Call = "󰃷 ",
	CaseStatement = "󱃙 ",
	Class = " ",
	Color = "󰏘 ",
	Constant = "󰏿 ",
	Constructor = " ",
	ContinueStatement = "→ ",
	Copilot = " ",
	Declaration = "󰙠 ",
	Delete = "󰩺 ",
	DoStatement = "󰑖 ",
	Enum = " ",
	EnumMember = " ",
	Event = " ",
	Field = " ",
	File = "󰈔 ",
	Folder = "󰉋 ",
	ForStatement = "󰑖 ",
	Function = "󰊕 ",
	H1Marker = "󰉫 ", -- Used by markdown treesitter parser
	H2Marker = "󰉬 ",
	H3Marker = "󰉭 ",
	H4Marker = "󰉮 ",
	H5Marker = "󰉯 ",
	H6Marker = "󰉰 ",
	Identifier = "󰀫 ",
	IfStatement = "󰇉 ",
	Interface = " ",
	Keyword = "󰌋 ",
	List = "󰅪 ",
	Log = "󰦪 ",
	Lsp = " ",
	Macro = "󰁌 ",
	MarkdownH1 = "󰉫 ", -- Used by builtin markdown source
	MarkdownH2 = "󰉬 ",
	MarkdownH3 = "󰉭 ",
	MarkdownH4 = "󰉮 ",
	MarkdownH5 = "󰉯 ",
	MarkdownH6 = "󰉰 ",
	Method = "󰆧 ",
	Module = "󰏗 ",
	Namespace = "󰅩 ",
	Null = "󰢤 ",
	Number = "󰎠 ",
	Object = "󰅩 ",
	Operator = "󰆕 ",
	Package = "󰆦 ",
	Pair = "󰅪 ",
	Property = " ",
	Reference = "󰦾 ",
	Regex = " ",
	Repeat = "󰑖 ",
	Scope = "󰅩 ",
	Snippet = "󰩫 ",
	Specifier = "󰦪 ",
	Statement = "󰅩 ",
	String = "󰉾 ",
	Struct = " ",
	SwitchStatement = "󰺟 ",
	Terminal = " ",
	Text = " ",
	Type = " ",
	TypeParameter = "󰆩 ",
	Unit = " ",
	Value = "󰎠 ",
	Variable = "󰀫 ",
	WhileStatement = "󰑖 ",
}

M.misc = {
	bug = " ",
	ellipsis = "…",
	git = " ",
	search = " ",
	vertical_bar = "│",
	vertical_bar_bold = "▐",
	two_big_arrow_right = "   ",
	single_big_arrow_right = " ",
}

--- Diagnostic severities.
M.diagnostics = {
	ERROR = " ",
	WARN = " ",
	HINT = " ",
	INFO = " ",
}

M.git = {
	branch = " ",
	add = " ",
	modified = " ",
	remove = " ",
	rename = "󰑕 ",
	change = "󱩼 ",
	task = " ",
	qmark = " ",
}
return M
