local S = require("config.settings")
local P = S.palette

hl.config({
    general = {
        layout = S.layout,
        gaps_in = 4,
        gaps_out = 5,
        gaps_workspaces = 50,
        border_size = 2,
        extend_border_grab_area = 10,
        resize_on_border = true,
        no_focus_fallback = true,
        allow_tearing = false,
        col = {
            active_border = P.primary,
            inactive_border = P.surface,
        },
        snap = {
            enabled = true,
            window_gap = 4,
            monitor_gap = 5,
            respect_gaps = true,
        },
    },
    group = {
        col = {
            border_active = P.secondary,
            border_inactive = P.surface,
            border_locked_active = P.error,
            border_locked_inactive = P.surface,
        },
        groupbar = {
            col = {
                active = P.secondary,
                inactive = P.surface,
                locked_active = P.error,
                locked_inactive = P.surface,
            },
        },
    },
    decoration = {
        rounding = 0,
        rounding_power = 2,
        active_opacity = 0.97,
        inactive_opacity = 0.84,
        fullscreen_opacity = 1,
        dim_inactive = true,
        dim_strength = 0.08,
        dim_special = 0.2,
        blur = {
            size = 12,
            passes = 2,
            xray = true,
            brightness = 1,
            noise = 0.035,
            contrast = 0.86,
            vibrancy = 0.6,
            vibrancy_darkness = 0.5,
            special = true,
            popups = true,
            popups_ignorealpha = 0.2,
            input_methods = true,
            input_methods_ignorealpha = 0.2,
        },
        shadow = {
            enabled = true,
            range = 20,
            offset = { 0, 3 },
            render_power = 4,
            color = P.shadow,
        },
    },
    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = false,
        precise_mouse_move = true,
    },
    misc = {
        font_family = "Iosevka Nerd Font",
        splash_font_family = "Iosevka Nerd Font",
        col = { splash = P.primary },
        middle_click_paste = false,
        enable_swallow = true,
        swallow_regex = "(" .. S.classes.terminals .. ")",
        vrr = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
    binds = {
        scroll_event_delay = 0,
        hide_special_on_workspace_change = true,
        workspace_back_and_forth = true,
    },
    xwayland = {
        force_zero_scaling = true,
    },
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})
