vim.opt_local.spell = true
vim.opt_local.wrap = true
vim.opt_local.list = false
vim.opt_local.wrapmargin = 113
vim.opt_local.statuscolumn = nil
vim.opt_local.number = false
vim.opt_local.relativenumber = false

local map = vim.keymap.set

map("n", "<leader>no", "<cmd>ObsidianOpen<cr>", { desc = "Open App" })
map("n", "<leader>nn", "<cmd>ObsidianNew<cr>", { desc = "New Note" })
map("n", "<leader>ns", "<cmd>ObsidianQuickSwitch<cr>", { desc = "Quick Swicth" })
map("n", "<leader>nf", "<cmd>ObsidianFollowLink<cr>", { desc = "Follow Link" })
map("n", "<leader>nb", "<cmd>ObsidianBacklinks<cr>", { desc = "Back Link" })
map("n", "<leader>nT", "<cmd>ObsidianTags<cr>", { desc = "Tags" })
map("n", "<leader>nt", "<cmd>ObsidianToday<cr>", { desc = "Today Note" })
map("n", "<leader>ny", "<cmd>ObsidianYesterday<cr>", { desc = "Yesterday Note" })
map("n", "<leader>nw", "<cmd>ObsidianTomorrow<cr>", { desc = "Tomorrow Note" })
map("n", "<leader>nd", "<cmd>ObsidianDailies<cr>", { desc = "Dailies Note" })
map("n", "<leader>nm", "<cmd>ObsidianTemplate<cr>", { desc = "Template" })
map("n", "<leader>ns", "<cmd>ObsidianSearch<cr>", { desc = "Search Note" })
map("v", "<leader>nl", "<cmd>ObsidianLink<cr>", { desc = "Link" })
map("v", "<leader>nN", "<cmd>ObsidianLinkNew<cr>", { desc = "Create New Link" })
map("n", "<leader>nL", "<cmd>ObsidianLinks<cr>", { desc = "Collect Link" })
map("n", "<leader>nx", "<cmd>ObsidianExtractNote<cr>", { desc = "Extract Note" })
map("n", "<leader>nw", "<cmd>ObsidianWorkspace<cr>", { desc = "Workspace" })
map("n", "<leader>np", "<cmd>ObsidianPasteImg<cr>", { desc = "Paste Image" })
map("n", "<leader>nr", "<cmd>ObsidianRename<cr>", { desc = "Rename Note" })
