return {
	{
		"ray-x/go.nvim",
		opts = {
			go = "go",
			goimports = "gopls",
			gofmt = "gopls",
			fillstruct = "gopls",
			max_line_len = 0,
			tag_transform = false,
			tag_options = "json",
			gotests_template = "",
			gotests_template_dir = "",
			comment_placeholder = "",
			icons = { breakpoint = "🧘", currentpos = "🏃" },
			verbose = false,
			lsp_cfg = false,
			lsp_gofumpt = true,
			lsp_on_attach = nil,
			lsp_keymaps = false,
			lsp_codelens = true,
			diagnostic = {
				hdlr = false,
				underline = true,
				virtual_text = { spacing = 2, prefix = "" },
				signs = { "", "", "", "" },
				update_in_insert = false,
			},
			lsp_document_formatting = true,
			lsp_inlay_hints = { enable = false },
			gocoverage_sign = "█",
			sign_priority = 5,
			dap_debug = true,
			dap_debug_keymap = true,
			dap_debug_gui = {
				floating = { border = "solid" },
				layouts = {
					{
						elements = {
							{ id = "scopes", size = 0.2 },
							{ id = "breakpoints", size = 0.2 },
							{ id = "stacks", size = 0.2 },
							{ id = "watches", size = 0.2 },
							{ id = "console", size = 0.2 },
						},
						position = "right",
						size = 55,
					},
					{ elements = { { id = "repl", size = 1 } }, position = "bottom", size = 8 },
				},
			},
			dap_debug_vt = { enabled_commands = true, all_frames = true },
			dap_port = 38697,
			dap_timeout = 15,
			dap_retries = 20,
			textobjects = false,
			test_runner = "go",
			verbose_tests = true,
			run_in_floaterm = false,
			trouble = false,
			test_efm = false,
			luasnip = false,
			iferr_vertical_shift = 4,
		},
		ft = { "go", "gomod" },
		-- build = ':lua require("go.install").update_all_sync()', -- if you need to install/update all binaries
	},
}
