return {
    "MeanderingProgrammer/render-markdown.nvim",
    ft = "markdown",
    opts = function()
        return {
            enabled = true,
            render_modes = { "n", "c", "t" },
            max_file_size = 10.0,
            debounce = 100,
            preset = "lazy",
            anti_conceal = {
                enabled = true,
                ignore = { code_background = false, sign = true },
                above = 0,
                below = 0,
            },
            padding = { highlight = "Normal" },
            heading = {
                enabled = true,
                render_modes = false,
                sign = true,
                position = "overlay",
                signs = { "󰫎 " },
                width = "full",
                left_margin = 0,
                left_pad = 1,
                right_pad = 1,
                min_width = 0,
                border = true,
                border_virtual = true,
                border_prefix = false,
                above = "▄",
                below = "▀",
            },
            paragraph = {
                enabled = true,
                render_modes = false,
                left_margin = 0,
                min_width = 0,
            },
            code = {
                enabled = true,
                render_modes = false,
                sign = true,
                style = "full",
                position = "left",
                language_pad = 0,
                language_name = true,
                disable_background = { "diff" },
                width = "full",
                left_margin = 0,
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = "thin",
                above = "▄",
                below = "▀",
                highlight = "RenderMarkdownCode",
                inline_pad = 1,
                highlight_inline = "RenderMarkdownCodeInline",
            },
            link = {
                enabled = true,
                render_modes = true,
                footnote = {
                    superscript = true,
                    prefix = "",
                    suffix = "",
                },
                image = "󰥶  ",
                email = "󰀓  ",
                hyperlink = "󰌹  ",
                highlight = "RenderMarkdownLink",
                wiki = { icon = "󱗖  ", highlight = "RenderMarkdownWikiLink" },
                custom = {
                    web = { pattern = "^http", icon = "󰖟 " },
                    youtube = { pattern = "youtube%.com", icon = "󰗃 " },
                    github = { pattern = "github%.com", icon = "󰊤 " },
                    neovim = { pattern = "neovim%.io", icon = " " },
                    stackoverflow = { pattern = "stackoverflow%.com", icon = "󰓌 " },
                    discord = { pattern = "discord%.com", icon = "󰙯 " },
                    reddit = { pattern = "reddit%.com", icon = "󰑍 " },
                },
            },
            sign = {
                enabled = true,
                highlight = "RenderMarkdownSign",
            },
            inline_highlight = {
                enabled = true,
                render_modes = false,
                highlight = "RenderMarkdownInlineHighlight",
            },
            indent = {
                enabled = true,
                render_modes = false,
                per_level = 2,
                skip_level = 1,
                skip_heading = false,
            },
            html = {
                enabled = true,
                render_modes = false,
                comment = {
                    conceal = true,
                    text = nil,
                    highlight = "RenderMarkdownHtmlComment",
                },
            },
        }
    end,
}
