return {
    {
        "3rd/image.nvim",
        ft = { "markdown" },
        opts = {
            backend = "kitty",
            processor = "magick_rock", -- or "magick_cli"
            integrations = {
                markdown = {
                    enabled = true,
                    clear_in_insert_mode = true,
                    download_remote_images = false,
                    only_render_image_at_cursor = false,
                    floating_windows = false,
                    filetypes = { "markdown", "vimwiki" },
                },
                html = { enabled = true },
                css = { enabled = true },
            },
            max_width = nil,
            max_height = nil,
            max_width_window_percentage = nil,
            max_height_window_percentage = 50,
            window_overlap_clear_enabled = false,
            window_overlap_clear_ft_ignore = { "snacks_notif", "scrollview", "scrollview_sign" },
            editor_only_render_when_focused = false,
            tmux_show_only_in_active_window = false,
            hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp", "*.avif" },
        },
    },
    {
        "MeanderingProgrammer/render-markdown.nvim",
        ft = { "markdown", "neorg" },
        opts = function()
            return {
                enabled = true,
                render_modes = { "n", "c", "t" },
                max_file_size = 10.0,
                debounce = 100,
                preset = "lazy",
                anti_conceal = {
                    enabled = true,
                    ignore = { code_background = false, sign = true },
                    above = 0,
                    below = 0,
                },
                padding = { highlight = "Normal" },
                heading = {
                    enabled = true,
                    render_modes = false,
                    sign = true,
                    position = "overlay",
                    signs = { "󰫎" },
                    width = "full",
                    left_margin = 0,
                    left_pad = 0,
                    right_pad = 0,
                    min_width = 0,
                    border = true,
                    border_virtual = true,
                    border_prefix = false,
                    above = "▄",
                    below = "▀",
                },
                paragraph = {
                    enabled = true,
                    render_modes = false,
                    left_margin = 0,
                    min_width = 0,
                },
                code = {
                    enabled = true,
                    render_modes = false,
                    sign = true,
                    style = "full",
                    position = "left",
                    language_pad = 1,
                    language_name = true,
                    disable_background = { "diff" },
                    width = "full",
                    left_margin = 0,
                    left_pad = 0,
                    right_pad = 0,
                    min_width = 0,
                    border = "thin",
                    above = "▄",
                    below = "▀",
                    highlight = "RenderMarkdownCode",
                    inline_pad = 1,
                    highlight_inline = "RenderMarkdownCodeInline",
                },
                link = {
                    enabled = true,
                    render_modes = true,
                    footnote = {
                        superscript = true,
                        prefix = "",
                        suffix = "",
                    },
                    image = "󰥶  ",
                    email = "󰀓  ",
                    hyperlink = "󰌹  ",
                    highlight = "RenderMarkdownLink",
                    wiki = { icon = "󱗖  ", highlight = "RenderMarkdownWikiLink" },
                    custom = {
                        web = { pattern = "^http", icon = "󰖟 " },
                        youtube = { pattern = "youtube%.com", icon = "󰗃 " },
                        github = { pattern = "github%.com", icon = "󰊤 " },
                        neovim = { pattern = "neovim%.io", icon = " " },
                        stackoverflow = { pattern = "stackoverflow%.com", icon = "󰓌 " },
                        discord = { pattern = "discord%.com", icon = "󰙯 " },
                        reddit = { pattern = "reddit%.com", icon = "󰑍 " },
                    },
                },
                sign = {
                    enabled = true,
                    highlight = "RenderMarkdownSign",
                },
                inline_highlight = {
                    enabled = true,
                    render_modes = false,
                    highlight = "RenderMarkdownInlineHighlight",
                },
                indent = {
                    enabled = true,
                    render_modes = false,
                    per_level = 2,
                    skip_level = 1,
                    skip_heading = false,
                },
                html = {
                    enabled = true,
                    render_modes = false,
                    comment = {
                        conceal = true,
                        text = nil,
                        highlight = "RenderMarkdownHtmlComment",
                    },
                },
            }
        end,
    },
}
