return {
    "epwalsh/obsidian.nvim",
    version = false,
    keys = {
        {
            "<leader>oo",
            function()
                vim.cmd.ObsidianOpen(vim.api.nvim_buf_get_name(0))
            end,
            desc = "Obsidian Open",
        },
        { "<leader>on", "<cmd>ObsidianNew<cr>", desc = "Obsidian New " },
        { "<leader>os", "<cmd>ObsidianQuickSwitch<cr>", desc = "Obsidian Switch" },
        { "<leader>ob", "<cmd>ObsidianBacklinks<cr>", desc = "Obsidian Backlinks" },
        { "<leader>od", "<cmd>ObsidianToday<cr>", desc = "Obsidian Today" },
        { "<leader>oy", "<cmd>ObsidianYesterday<cr>", desc = "Obsidian Yesterday" },
        { "<leader>oD", "<cmd>ObsidianTomorrow<cr>", desc = "Obsidian Tomorrow" },
        { "<leader>ot", "<cmd>ObsidianTemplate<cr>", desc = "Obsidian Template" },
        { "<leader>oT", "<cmd>ObsidianNewFromTemplate<cr>", desc = "Obsidian New Template" },
        { "<leader>oc", "<cmd>ObsidianTOC<cr>", desc = "Obsidian ToC" },
    },
    opts = {
        workspaces = { { name = "Notes", path = os.getenv("HOME") .. "/Notes", overrides = {} } },
        notes_subdir = nil,
        log_level = vim.log.levels.INFO,
        completion = { nvim_cmp = true, min_chars = 2 },
        new_notes_location = "current_dir",
        wiki_link_func = "use_path_only",
        preferred_link_style = "wiki",
        use_advanced_uri = true,
        disable_frontmatter = true,
        sort_by = "modified",
        sort_reversed = true,
        search_max_lines = 1000,
        open_notes_in = "current",
        ui = { enable = false },
        templates = { folder = "Templates" },
        picker = { name = "fzf-lua" },
        daily_notes = {
            folder = "00 Inbox",
            date_format = "%Y%m%d",
            alias_format = "%Y%m%d",
            default_tags = { "daily" },
            template = nil,
        },
    },
}
